SELECT TOP (1000) [Id]
      ,[MaSV]
      ,[TenSV]
      ,[NgaySinh]
      ,[GioiTinh]
      ,[QueQuan]
      ,[NgayNhapHoc]
      ,[MaLop]
      ,[MaKhoa]
      ,[MaCVHT]
  FROM [ds_QLSV].[dbo].[SinhVien]

